config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tweets#index"

  #tweets controllerını tanımladık
  resources :tweets do
    resources :comments, controller: "tweets/comments"
  end
  
  resources :users, except: [:destroy] do
    resources :tweets, controller: "users/tweets"
  end

  namespace :api do
    namespace :v1 do
      resources :users
      resources :tweets
    end
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  #tweetin hangi kullanıcıya ait olduğunu belirttik.
  belongs_to :user
  #bir tweet birden fazla yoruma sahip olabilr
  has_many :comments, dependent: :destroy
end

app/controllers/api/v1/tweets_controller.rb
class Api::V1::TweetsController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false
  
  def index
    user = User.find(params[:user_id])
    tweets = user.tweets
  
    render json: {
      user_id: user.id,
      tweets: tweets.as_json(only: [:id, :body, :created_at, :updated_at])
    } and return
  rescue ActiveRecord::RecordNotFound
    render json: { error: "User not found" }, status: :not_found
  end

  def show
    tweet = Tweet.includes(:comments).find(params[:id])

    render json: {
      tweet: {
        id: tweet.id,
        body: tweet.body,
        created_at: tweet.created_at,
        updated_at: tweet.updated_at
      },
      comments: tweet.comments.map do |comment| 
        {
          id: comment.id,
          body: comment.body,
          created_at: comment.created_at,
          updated_at: comment.updated_at
        }
      end
    }
  rescue
    render json: {error: "Tweet not found"}, status: :not_found
  end
end

app/controllers/tweets/comments_controller.rb
class Tweets::CommentsController < ApplicationController
  before_action :set_tweet
  before_action :set_comment, only: [:edit, :update, :destroy]
  
  def create
    @comment = @tweet.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save 
      redirect_to tweet_path(@tweet), notice: "Comment added successfully."
    else
      redirect_to tweet_path(@tweet), alert: "Failed to add comment."
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to tweet_path(@tweet)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    redirect_to tweet_path(@tweet), status: :see_other
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end

  def set_tweet 
    @tweet = Tweet.find(params[:tweet_id])
  end

  def set_comment
    @comment = @tweet.comments.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  #tweetleri listeler
  def index
    @tweets = Tweet.all.order(created_at: :desc)
  end
  #tweet detay sayfası
  def show
    @comments = @tweet.comments 
  end
  #yeni tweet oluşturma sayfası
  def new
    @tweet = Tweet.new 
  end
  #yeni tweet oluşturma işlemi
  def create
    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      redirect_to root_path, notice: "The tweet was created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end
  #tweet düzenleme sayfası
  def edit
  end
  #tweet güncelleme işlemi
  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet
    else 
      render :edit, status: :unprocessable_entity
    end
  end
  #tweet silme işlemi
  def destroy
    @tweet.destroy
    redirect_to root_path(@tweet), status: :see_other
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body, :user_id)
  end
  
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def authorize_user!
    redirect_to tweets_path, alert: "You are not authorized to perform this action." unless @tweet.user == current_user
  end
end

app/controllers/users/tweets_controller.rb
class Users::TweetsController < ApplicationController
  def create
    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      redirect_to tweets_path, notice: "Tweet was successfully created."
    else
      render :new
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_comment.html.erb
<li class="p-4 bg-gray-100 rounded-lg shadow-md">
    <p class="text-gray-700"><%= comment.body %></p>
    <p class="text-sm text-gray-500">Posted at: <%= comment.created_at.strftime("%b %d, %Y %H:%M") %></p>
    <div class="flex justify-end mt-2">
      <%= link_to [comment.tweet, comment], data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } do %>
        <%= image_tag("trash-icon.svg", class: "h-5 w-5 mr-2")%>
      <% end %>
      <%= link_to edit_tweet_comment_path(comment.tweet, comment) do %>
        <%= image_tag("edit-icon.svg", class: "h-5 w-5 mr-2")%>
      <% end %>
    </div>
</li>

app/views/tweets/_comment_form.html.erb
    <%= form_with model: [tweet, Comment.new] do |form| %>
      <div class="flex justify-center items-center w-full px-2 py-2 focus:outline-none focus:ring focus:ring-yellow-200 mb-2">
          <%= form.text_area :body, class: "w-full rounded-lg border border-gray-300"  %>
      </div>
      <%= form.submit "Send", class: "w-full bg-blue-600 text-white font-semibold py-2 px-2 rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring focus:ring-blue-200 mb-2" %>
    <% end %>

app/views/tweets/_sidebar.html.erb
<div class="flex flex-col w-full mt-16">
    <% menu_items =[ 
        { name: "Home", path: root_path, icon: "home-icon.svg" },
        { name: "Explore", path: root_path, icon: "explore-icon.svg" },
        { name: "Notifications", path: root_path, icon: "notifications-icon.svg" },
        { name: "Messages", path: root_path, icon: "messages-icon.svg" },
        { name: "Bookmarks", path: root_path, icon: "bookmarks-icon.svg" },
        { name: "User List", path: users_path, icon: "users-icon.svg" },
        { name: "Profile", path: root_path, icon: "profile-icon.svg" },
        { name: "More", path: root_path, icon: "more-icon.svg" },
        { name: "Log Out", path: destroy_user_session_path, method: :delete, icon: "logout-icon.svg" },
    ] %>
    
    <% menu_items.each do |item| %>
        <%= link_to item[:path], class: "flex items-center p-2 rounded-lg hover:bg-blue-100 transition duration-200 mb-2", data: {turbo_method: item[:method] || :get} do %>
            <%= image_tag item[:icon], class: "w-6 h-6" %>
            <p class="text-gray-800 text-md font-medium ml-3"><%= item[:name] %></p>
        <% end %>
    <% end %>
</div>

app/views/tweets/_tweet.html.erb
 <li class="p-4 bg-white rounded-lg shadow-md">
  <div class="flex justify-between items-center mb-2">
    <div class="flex items-center">
      <div class="w-16 h-16 rounded-full overflow-hidden mr-4">
        <%= link_to user_path(tweet.user) do %>
          <% if tweet.user.profile_picture.attached? %>
            <%= image_tag tweet.user.profile_picture, class: "w-full h-full object-cover" %>
          <% else %>
            <%= image_tag("default-icon.svg", class: "w-full h-full object-cover") %>
          <% end %>
        <% end %>
      </div>
      <%= link_to tweet.user.username, user_path(tweet.user), class: "font-bold text-lg hover:underline" %>
    </div>
    <small class="text-gray-500 text-sm">
      <%= tweet.created_at.strftime("%b %d, %Y") %>
    </small>
  </div>
  <p class="text-gray-800">
    <%= link_to tweet.body, tweet_path(tweet) %>
  </p>
  <div class="flex justify-end mt-2">
    <%= link_to [tweet], data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } do %>
      <%= image_tag("trash-icon.svg", class: "h-6 w-6 mr-2")%>
    <% end %>
    <%= link_to edit_tweet_path(tweet) do %>
      <%= image_tag("edit-icon.svg", class: "h-6 w-6 mr-2")%>
    <% end %>
    <%= link_to tweet_path(tweet) do %>
      <%= image_tag("comments-icon.svg", class: "h-6 w-6") %>
    <% end %>
  </div>
</li>

app/views/tweets/edit.html.erb
<div class="flex justify-center items-center w-full p-4">
    <div class="col-span-6 bg-gray-100 p-4 rounded-lg shadow-md">
      <div class="flex flex-col p-2 mb-2 bg-gray-100 rounded-lg shadow-md">
        <h1 class="font-bold text-xl"><%= @tweet.user.username %></h1>
        <h1><%= @tweet.body %></h1>
      </div>
      <div class="p-2">
        <h2 class="text-base font-semibold">edit tweet</h2>
        <%= form_with model: @tweet do |form| %>
          <div class="flex justify-center items-center w-full px-2 py-2 focus:outline-none focus:ring focus:ring-yellow-200 mb-2">
            <%= form.text_area :body, class: "w-full rounded-lg border border-gray-300"%>
          </div>
          <%= form.submit "Save", class: "w-full bg-blue-600 text-white font-semibold py-2 px-2 rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring focus:ring-blue-200 mb-2" %>
        <% end %>
      </div>
    </div>
</div>

app/views/tweets/index.html.erb
<div class="grid grid-cols-12 gap-4 w-full p-4">
    <div class="col-span-3 bg-gray-100 p-4 rounded-xl shadow-md">
        <%= render "sidebar" %>
    </div>

    <div class="col-span-6 bg-gray-100 p-4 rounded-xl shadow-md">
        <div class="flex justify-between mb-4">
            <h1 class="text-3xl text-blue-600 font-bold">Tweets</h1>
            <%= link_to "New", new_tweet_path, class: "px-4 py-2 bg-blue-600 text-white text-xl rounded-xl" %>
        </div>
        <ul class="space-y-4">
            <% @tweets.each do |tweet| %>
                <%= render "tweet", tweet: tweet %>
            <% end %>
        </ul>
    </div>

    <div class="col-span-3 bg-gray-100 p-4 rounded-xl shadow-md">
        <h2 class="text-lg font-bold text-gray-700">Explore</h2>
        <p class="text-gray-600 mt-2">Coming soon...</p>
    </div>
</div>

app/views/tweets/new.html.erb
<div class="w-full">
  <h1 class="text-3xl text-blue-600 font-bold">New Tweet</h1>
  <%= form_with model: @tweet do |form| %>
    <div>
      <% @tweet.errors.full_messages.each do |message| %>
        <p class="text-red-600"><%= message %></p>
      <% end %>
    </div>

    <div class="mt-4 w-full">
      <%= form.label :body, class: "block text-md text-blue-600" %>
      <%= form.text_area :body, class: "w-full h-32 border border-blue-600 rounded-xl p-2" %>
    </div>

    <%= form.submit "Tweetle", class: "px-4 py-2 bg-blue-600 text-white text-md rounded-xl mt-4" %>
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class="flex justify-center items-center w-full p-4">
  <div class="col-span-6 bg-gray-100 p-4 rounded-lg shadow-md">
    <div class="flex flex-col p-2 mb-2 bg-gray-100 rounded-lg shadow-md">
      <h1 class="font-bold text-xl"><%= @tweet.user.username %></h1>
      <h1><%= @tweet.body %></h1>
    </div>
    <div class="p-2">
      <h2 class="text-base font-semibold">comments</h2>
      <%= render "comment_form", tweet: @tweet %>
      <ul class="space-y-2">
        <% @comments.each do |comment| %>
          <%= render "comment", comment: comment%>
        <% end %>
        <% if @comments.empty? %>
          <p class="text-gray-500 mt-4">No comments yet. Be the first to comment!</p>
        <% end %>
      </ul>
    </div>
  </div>
</div>