config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tweets#index"

  #tweets controllerını tanımladık
  resources :tweets do
    resources :comments, controller: "tweets/comments"
  end
  
  resources :users, except: [:destroy] do
    resources :tweets, controller: "users/tweets"
  end

  namespace :api do
    namespace :v1 do
      resources :users
      resources :tweets
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #bir kullanıcının birden fazla tweeti olabilir
  has_many :tweets
  #bir kulanıcının birden fazla yorumu olabilr
  has_many :comments
  #email ve username alanlarının boş olmamasını ve benzersiz olması gerektiğini belirttik.
  validates :email, :username, presence: true, uniqueness: true 
  #her kullanıcının bir profil resmi olmalı
  has_one_attached :profile_picture
  #first_name ve last_name alanlarının boş olmaması gerektiğini belirttik.
  validates :first_name, :last_name, presence: true
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false
 
  def index
    if params[:search].present?
      query = "%#{params[:search]}% "
      users = User.where("username ILIKE ?", query)
    else
      users = User.all
    end

    render json: users.select(:id, :username), status: :ok
  end

  def show
    user = User.find_by(id: params[:id])

    if user
      render json: {
        id: user.id,
        first_name: user.first_name,
        last_name: user.last_name,
        email: user.email,
        username: user.username
      }, status: :ok
    else
      render json: { error: "User not found" }, status: :not_found
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :email, :password, :password_confirmation])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/tweets_controller.rb
class Users::TweetsController < ApplicationController
  def create
    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      redirect_to tweets_path, notice: "Tweet was successfully created."
    else
      render :new
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    if params[:query].present? #.present ile kullanıcının bir arama sorgusu gönderip göndermediğini kontrol eder.
      query = "%#{params[:query]}%" #istekte gönderilen parametreleri alıyoruz
      @users = User.where("first_name ILIKE ? OR last_name ILIKE ? OR username ILIKE ?", query, query, query) 
    else
      @users = User.all
    end
  end

  def show
    @tweets = @user.tweets.order(created_at: :desc)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:profile_picture, :email, :first_name, :last_name, :username)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_tweet.html.erb
<li class="border-b border-gray-200 pb-4">
	<p class="text-gray-700"><%= tweet.body %></p>
	<p class="text-sm text-gray-500 mt-2">Posted at: <%= tweet.created_at.strftime("%d %b %Y, %H:%M") %></p>
	<div class="flex justify-end mt-2">
		<%= link_to tweet_path(tweet), data: {
			turbo_method: :delete,
			turbo_confirm: "Are you sure you want to delete this tweet?"
		} do %>
			<%= image_tag("trash-icon.svg", class: "h-5 w-5 mr-2") %>
		<% end %>
		<%= link_to edit_tweet_path(tweet) do %>
			<%= image_tag("edit-icon.svg", class: "h-5 w-5 mr-2") %>
		<% end %>
	</div>
</li>

app/views/users/_tweet_form.html.erb
<%= form_with model: [@user, Tweet.new] do |form| %>
	<div class="flex justify-center items-center w-full px-2 py-2 focus:outline-none focus-ring-blue-200 mb-2">
		<%= form.text_area :body, class: "w-full rounded-lg border border-gray-300" %>
	</div>
	<%= form.submit "Send", class: "w-full bg-blue-600 text-white font-semibold py-2 px-2 rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring focus:ring-blue-200 mb-2" %>
<% end %>  

app/views/users/edit.html.erb
<div class="flex justify-center items-center min-h-screen bg-gray-50 mx-auto">
  <div class="w-full max-w-2xl bg-white p-6 rounded-lg shadow-lg">
    <h1 class="text-2xl font-bold text-gray-800 text-center mb-6">Edit Profile</h1>
    <%= form_with model: @user, local: true do |form| %>
      <div class="mb-6 flex flex-col items-center">
        <% if @user.profile_picture.attached? %>
          <div class="mb-4">
            <%= image_tag @user.profile_picture, class: "w-28 h-28 rounded-full shadow-md object-cover" %>
          </div>
          <p class="text-sm text-gray-600">Change your profile picture</p>
        <% else %>
          <p class="text-sm text-gray-600 mb-4">No profile picture uploaded.</p>
          <p class="text-sm text-gray-600">Upload a profile picture:</p>
        <% end %>
        <div class="flex justify-center">
          <%= form.file_field :profile_picture, class: "mt-2  text-sm file:mr-4 file:ml-8 file:py-2 file:px-4 file:rounded-full file:border file:border-gray-300 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100" %>
        </div>
      </div>

      <div class="mb-4">
        <%= form.label :email, "Email", class: "block font-medium text-gray-700 mb-1" %>
        <%= form.text_field :email, value: @user.email, class: "block w-full border border-gray-300 rounded-lg p-2 focus:ring-blue-500 focus:border-blue-500" %>
      </div>

      <div class="mb-4">
        <%= form.label :first_name, "First Name", class: "block font-medium text-gray-700 mb-1" %>
        <%= form.text_field :first_name, value: @user.first_name, class: "block w-full border border-gray-300 rounded-lg p-2 focus:ring-blue-500 focus:border-blue-500" %>
      </div>

      <div class="mb-4">
        <%= form.label :last_name, "Last Name", class: "block font-medium text-gray-700 mb-1" %>
        <%= form.text_field :last_name, value: @user.last_name, class: "block w-full border border-gray-300 rounded-lg p-2 focus:ring-blue-500 focus:border-blue-500" %>
      </div>

      <div class="mb-4">
        <%= form.label :username, "Username", class: "block font-medium text-gray-700 mb-1" %>
        <%= form.text_field :username, value: @user.username, class: "block w-full border border-gray-300 rounded-lg p-2 focus:ring-blue-500 focus:border-blue-500" %>
      </div>

      <div class="flex justify-end">
        <%= form.submit "Update", class: "bg-blue-500 text-white px-6 py-2 rounded-lg hover:bg-blue-600 transition duration-200" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="flex flex-col justify-center items-center w-full p-4 bg-gray-100">
  <div class="mb-4 justify-center">
    <%= form_with url: "/users", method: :get, class:"mb-4" do |form| %>
    <%= form.label :query, "Search users:", class: "block text-gray-700 font-bold mb-2" %>
    <%= form.search_field :query, class: "border border-gray-300 rounded-lg p-2" %>
    <%= form.submit "Search", class: "bg-blue-500 text-white rounded-lg px-4 py-2" %>
  <% end %>
  </div>
  <ul class="flex flex-col justify-center gap-6 rounded-lg shadow-lg">
    <% @users.each do |user| %>
      <li class="flex items-center bg-gray-50 border border-gray-300 rounded-lg p-4 shadow-md">
        <div class="w-16 h-16 rounded-full overflow-hidden mr-4">
          <%= link_to user_path(user) do %>
             <% if user.profile_picture.attached? %>
                <%= image_tag user.profile_picture %>
              <% else %>
                <%= image_tag("default-icon.svg") %>
              <% end %>
          <% end %>
        </div>
        <div class="flex flex-col">
          <%= link_to user_path(user) do %>
            <h2 class="text-xl font-bold text-gray-800"><%= "#{user.first_name} #{user.last_name}"%></h2>
            <p class="text-sm text-gray-400"><%= user.username %></p>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="w-full flex flex-col items-center">
  <div class="flex flex-col w-full max-w-3xl justify-center items-center bg-gray-100 p-4 rounded-lg shadow-md">
    
    <div class="relative flex flex-col items-center w-full rounded-lg shadow-md p-6 mb-6 bg-white">
      <% if current_user == @user %>
      <div class="absolute top-4 right-4">
          <%= link_to edit_user_path(@user) do %>
            <%= image_tag("edit-icon.svg", class: "h-6 w-6") %>
          <% end %>
        </div>
      <% end %>
      <div class="flex flex-col items-center">
        <% if @user.profile_picture.attached? %>
          <%= image_tag @user.profile_picture, class: "w-24 h-24 rounded-full object-cover mb-4" %>
        <% else %>
          <%= image_tag("default-icon.svg", class: "w-24 h-24 rounded-full object-cover mb-4") %>
        <% end %>
        <h1 class="text-xl font-bold text-gray-800"><%= "#{@user.first_name} #{@user.last_name}"%></h1>
        <h1 class="text-sm text-gray-400"><%= @user.username %></h1>
      </div>
    </div>

    <% if current_user == @user %>
      <div class="w-full bg-white rounded-lg shadow-md p-4">
        <h2 class="text-lg font-semibold text-gray-800 mb-2">Create a new tweet!</h2>
        <%= render "tweet_form", tweet: @tweet %>
      </div>
    <% end %>

    <div class="w-full bg-white rounded-lg shadow-md p-4">
      <h2 class="text-lg font-semibold text-gray-800 mb-4 mt-4">Tweets by <%= @user.username %></h2>
      <ul class="space-y-4">
        <% @tweets.each do |tweet| %>
          <%= render "tweet", tweet: tweet %>
        <% end %>
      </ul>
      <% if @tweets.empty? %>
        <p class="text-gray-500 text-center mt-4">This user hasn't posted any tweets yet.</p>
      <% end %>
    </div>
  </div>
</div>